# appveyor integration for the hid-io device daemon

# Select environments
# NOTE: x86_64-pc-windows-gnu isn't supported
environment:
  matrix:
  # stable
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: stable
  - TARGET: i686-pc-windows-msvc
    CHANNEL: stable
  - TARGET: i686-pc-windows-gnu
    CHANNEL: stable
    MSYS_BITS: 32
  # min-version
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: 1.17.0
  - TARGET: i686-pc-windows-msvc
    CHANNEL: 1.17.0
  - TARGET: i686-pc-windows-gnu
    CHANNEL: 1.17.0
    MSYS_BITS: 32
  # beta
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: beta
  - TARGET: i686-pc-windows-msvc
    CHANNEL: beta
  - TARGET: i686-pc-windows-gnu
    CHANNEL: beta
    MSYS_BITS: 32
  # environment variables
  RUST_BACKTRACE: full

# Setup rust compiler
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin
  - rustc -Vv
  - cargo -Vv

build: false

# Build commands
test_script:
  - cargo build --verbose --color=always
  - cargo test --verbose --color=always

